title: HaxFootball Brazil
description: A maior comunidade de futebol americano do Haxball
remote_theme: pmarsceill/just-the-docs
baseurl: ""
permalink: pretty

url: https://haxfootballbrazil.github.io/haxfootballbrazil.github.io

aux_links:
  Template Repository: https://github.com/haxfootballbrazil/haxfootballbrazil.github.io

color_scheme: dark