title: HaxFootball Brazil
description: A maior comunidade de futebol americano do Haxball
remote_theme: just-the-docs/just-the-docs
baseurl: ""
permalink: pretty

url: https://haxfootballbrazil.github.io/haxfootballbrazil.github.io

aux_links:
  Template Repository: https://github.com/haxfootballbrazil/haxfootballbrazil.github.io

color_scheme: dark

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: Tactical Board
    url: https://haxfootballbrazil.github.io/tactical-board/